/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 95f552a4-4250-4d9c-86f4-44be85221c55 instead of MulleObjCValueFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCValueFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCValueFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCValueFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCValueFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCValueFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCValueFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCValueFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCValueFoundation/MulleObjCValueFoundation.h>   // MulleObjCValueFoundation

#ifdef __has_include
# if __has_include( "_MulleScionHTMLPreprocessor-include.h")
#  include "_MulleScionHTMLPreprocessor-include.h"
# endif
#endif

