# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
   if( NOT MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY)
      find_library( MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}Foundation${CMAKE_STATIC_LIBRARY_SUFFIX} Foundation)
      message( STATUS "MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY is ${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}")
   
      # the order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need
      if( MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY)
         set( ALL_LOAD_DEPENDENCY_LIBRARIES
            ${ALL_LOAD_DEPENDENCY_LIBRARIES}
            ${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT "${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT}" DIRECTORY)
   
         # search for DependenciesAndLibraries.cmake to include
         foreach( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME "Foundation")
            set( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT}/include/${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( EXISTS "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake")
               unset( MULLE_SCIONH_TMLPREPROCESSOR_DEFINITIONS)
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}")
               # we only want top level INHERIT_OBJC_LOADERS, so disable them
               if( NOT NO_INHERIT_OBJC_LOADERS)
                  set( NO_INHERIT_OBJC_LOADERS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
               set( NO_INHERIT_OBJC_LOADERS ON)
               #
               include( "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake")
               #
               list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
               #
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}")
               set( INHERITED_DEFINITIONS
                  ${INHERITED_DEFINITIONS}
                  ${MULLE_SCIONH_TMLPREPROCESSOR_DEFINITIONS}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            else()
               message( STATUS "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake not found")
            endif()
         endforeach()
   
         # search for objc-loader.inc in include directory
         # this can be turned  off (see above)
         if( NOT NO_INHERIT_OBJC_LOADERS)
            foreach( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME "Foundation")
               set( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_FILE "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT}/include/${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME}/objc-loader.inc")
               if( EXISTS "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_FILE}")
                  set( INHERITED_OBJC_LOADERS
                     ${INHERITED_OBJC_LOADERS}
                     ${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_FILE}
                     CACHE INTERNAL "need to cache this"
                  )
                  break()
               endif()
            endforeach()
         endif()
      else()
         message( FATAL_ERROR "MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY was not found")
      endif()
   endif()
endif()


if( NOT MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY)
   find_library( MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-buffer${CMAKE_STATIC_LIBRARY_SUFFIX} mulle-buffer)
   message( STATUS "MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY is ${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}")

   # the order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need
   if( MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY)
      set( DEPENDENCY_LIBRARIES
         ${DEPENDENCY_LIBRARIES}
         ${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT "${MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT}" DIRECTORY)

      # search for DependenciesAndLibraries.cmake to include
      foreach( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME "mulle-buffer")
         set( _TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_ROOT}/include/${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_SCIONH_TMLPREPROCESSOR_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}")
            # we only want top level INHERIT_OBJC_LOADERS, so disable them
            if( NOT NO_INHERIT_OBJC_LOADERS)
               set( NO_INHERIT_OBJC_LOADERS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
            set( NO_INHERIT_OBJC_LOADERS ON)
            #
            include( "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake")
            #
            list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_SCIONH_TMLPREPROCESSOR_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_SCIONH_TMLPREPROCESSOR_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
   else()
      message( FATAL_ERROR "MULLE_SCIONH_TMLPREPROCESSOR_LIBRARY was not found")
   endif()
endif()
