# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleScionHTMLPreprocessor.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleScionHTMLPreprocessor.m
)

set( STANDALONE_SOURCES
src/MulleScionHTMLPreprocessor-standalone.m
)
